Initialized Svelte and Tailwind
adulbrich/osu-fsf pull request #33
Opened 2023-11-09 01:56 UTC by remingtr

Initialized Svelte with Typescript. Instructions for running on a local server are in the README

2023-11-09 02:01 UTC, aidanwroos approved these changes
Works on my machine with no issue

2023-11-09 05:38 UTC, fuenteed approved these changes
Worlds on my local machine

2023-11-10 00:07 UTC, adulbrich requested changes
Please rename `src-tailwind-svelte` to `src-web-app` to follow conventions agreed upon.

2023-11-14 19:47 UTC, adulbrich approved these changes

2023-11-14 19:47 UTC, merged